version: '3.7'

services:
  abuseipdb:
    build:
      context: ./abuseipdb
    container_name: abuseipdb
    environment:
      - API_KEY=YOUR_ABUSEIPDB_API_KEY
    ports:
      - "8080:8080"

  virustotal:
    build:
      context: ./virustotal
    container_name: virustotal
    environment:
      - API_KEY=YOUR_VIRUSTOTAL_API_KEY
    ports:
      - "8081:8081"

  automation:
    build:
      context: ./automation
    container_name: automation
    volumes:
      - ./scripts:/scripts
    command: /scripts/run.sh
